---
argocd_version:                            "{{ lookup('env', 'ARGOCD_VERSION') }}"
argocd_helm_chart_version:                 "{{ lookup('env', 'ARGOCD_HELM_CHART_VERSION') }}"
aws_efs_csi_driver_version:                "{{ lookup('env', 'AWS_EFS_CSI_DRIVER_VERSION') }}"
aws_region:                                "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
beats_exporter_version:                    "{{ lookup('env', 'BEATS_EXPORTER_VERSION') }}"
bird_exporter_version:                     "{{ lookup('env', 'BIRD_EXPORTER_VERSION') }}"
cerebro_version:                           "{{ lookup('env', 'CEREBRO_VERSION') }}"
curator_version:                           "{{ lookup('env', 'CURATOR_VERSION') }}"
curl_version:                              "{{ lookup('env', 'CURL_VERSION') }}"
default_backend_version:                   "{{ lookup('env', 'DEFAULT_BACKEND_VERSION') }}"
dex_k8s_authenticator_version:             "{{ lookup('env', 'DEX_K8S_AUTHENTICATOR_VERSION') }}"
dex_pg_version:                            "{{ lookup('env', 'DEX_PG_VERSION') }}"
dex_version:                               "{{ lookup('env', 'DEX_VERSION') }}"
elastalert_version:                        "{{ lookup('env', 'ELASTALERT_VERSION') }}"
elasticsearch_exporter_version:            "{{ lookup('env', 'ELASTICSEARCH_EXPORTER_VERSION') }}"
elasticsearch_version:                     "{{ lookup('env', 'ELASTICSEARCH_VERSION') }}"
env_domain:                                "{{ lookup('env', 'ENV_DOMAIN') }}"
env_name:                                  "{{ lookup('env', 'ENV_NAME') }}"
env_profile:                               "{{ lookup('env', 'ENV_PROFILE') }}"
env_type:                                  "{{ lookup('env', 'ENV_TYPE') }}"
external_dns_version:                      "{{ lookup('env', 'EXTERNAL_DNS_VERSION') }}"
filebeat_version:                          "{{ lookup('env', 'FILEBEAT_VERSION') }}"
grafana_version:                           "{{ lookup('env', 'GRAFANA_VERSION') }}"
http_relay_nginx_version:                  "{{ lookup('env', 'HTTP_RELAY_NGINX_VERSION') }}"
ingress_controller_version:                "{{ lookup('env', 'INGRESS_CONTROLLER_VERSION') }}"
ingress_instance:                          "{{ lookup('env', 'INGRESS_INSTANCE') }}"
ingress_memcached_version:                 "{{ lookup('env', 'INGRESS_MEMCACHED_VERSION') }}"
memcached_exporter_version:                "{{ lookup('env', 'MEMCACHED_EXPORTER_VERSION') }}"
karma_version:                             "{{ lookup('env', 'KARMA_VERSION') }}"
kibana_version:                            "{{ lookup('env', 'KIBANA_VERSION') }}"
kops_admin_access:                         "{{ lookup('env', 'KOPS_ADMIN_ACCESS') }}"
kops_cluster_name:                         "{{ lookup('env', 'KOPS_CLUSTER_NAME') }}"
kops_arm_image:                            "{{ lookup('env', 'KOPS_ARM_IMAGE') }}"
kops_image:                                "{{ lookup('env', 'KOPS_IMAGE') }}"
kops_vpc_cidr:                             "{{ lookup('env', 'KOPS_VPC_CIDR') }}"
kops_vpc_peering_destination_vpc_cidr:     "{{ lookup('env', 'KOPS_VPC_PEERING_DESTINATION_CIDR') }}"
kops_vpc_peering_destination_vpc_cidr_pro: "{{ lookup('env', 'KOPS_VPC_PEERING_DESTINATION_CIDR_PRO') }}"
kops_vpc_peering_destination_vpc_id:       "{{ lookup('env', 'KOPS_VPC_PEERING_DESTINATION_ID') }}"
kops_vpc_peering_destination_vpc_id_pro:   "{{ lookup('env', 'KOPS_VPC_PEERING_DESTINATION_ID_PRO') }}"
kube_bench_version:                        "{{ lookup('env', 'KUBE_BENCH_VERSION') }}"
kube_state_metrics_version:                "{{ lookup('env', 'KUBE_STATE_METRICS_VERSION') }}"
kube_webhook_certgen_version:              "{{ lookup('env', 'KUBE_WEBHOOK_CERTGEN_VERSION') }}"
kubernetes_csi_external_provisioner_ver:   "{{ lookup('env', 'KUBERNETES_CSI_EXTERNAL_PROVISIONER_VER') }}"
kubernetes_csi_livenessprobe_version:      "{{ lookup('env', 'KUBERNETES_CSI_LIVENESSPROBE_VERSION') }}"
kubernetes_csi_node_driver_registrar_ver:  "{{ lookup('env', 'KUBERNETES_CSI_NODE_DRIVER_REGISTRAR_VER') }}"
kubernetes_dashboard_version:              "{{ lookup('env', 'KUBERNETES_DASHBOARD_VERSION') }}"
kubernetes_replicator_version:             "{{ lookup('env', 'KUBERNETES_REPLICATOR_VERSION') }}"
kubernetes_version:                        "{{ lookup('env', 'KUBERNETES_VERSION') }}"
ldap_apps_users:                           "{{ lookup('env', 'APPS') }}"
ldap_users:                                "{{ lookup('env', 'USERS') }}"
ldap_version:                              "{{ lookup('env', 'LDAP_VERSION') }}"
le_api_env:                                "{{ lookup('env', 'LE_API_ENV') }}"
metrics_scrapper_version:                  "{{ lookup('env', 'METRICS_SCRAPPER_VERSION') }}"
nginx_ldapauth_proxy_chart_version:        "{{ lookup('env', 'NGINX_LDAPAUTH_PROXY_CHART_VERSION') }}"
nginx_ldapauth_proxy_version:              "{{ lookup('env', 'NGINX_LDAPAUTH_PROXY_VERSION') }}"
oauth2_proxy_version:                      "{{ lookup('env', 'OAUTH2_PROXY_VERSION') }}"
phusion_baseimage_version:                 "{{ lookup('env', 'PHUSION_BASEIMAGE_VERSION') }}"
project:                                   "{{ lookup('env', 'PROJECT') }}"
prometheus_adapter_version:                "{{ lookup('env', 'PROMETHEUS_ADAPTER_VERSION') }}"
prometheus_alert_manager_version:          "{{ lookup('env', 'PROMETHEUS_ALERT_MANAGER_VERSION') }}"
prometheus_blackbox_exporter_version:      "{{ lookup('env', 'PROMETHEUS_BLACKBOX_EXPORTER_VERSION') }}"
prometheus_node_exporter_version:          "{{ lookup('env', 'PROMETHEUS_NODE_EXPORTER_VERSION') }}"
prometheus_operator_chart_version:         "{{ lookup('env', 'PROMETHEUS_OPERATOR_CHART_VERSION') }}"
prometheus_operator_version:               "{{ lookup('env', 'PROMETHEUS_OPERATOR_VERSION') }}"
prometheus_version:                        "{{ lookup('env', 'PROMETHEUS_VERSION') }}"
root_dir:                                  "{{ lookup('env', 'HOME') }}/app"
rstudio_version:                           "{{ lookup('env', 'RSTUDIO_VERSION') }}"
scala_cli_version:                         "{{ lookup('env', 'SCALA_CLI_VERSION') }}"
skip_validation:                           "{{ lookup('env', 'SKIP_VALIDATION') }}"
store_rds_admin_password:                  "{{ lookup('env', 'STORE_RDS_ADMIN_PASSWORD') }}"
store_rds_admin_username:                  "{{ lookup('env', 'STORE_RDS_ADMIN_USERNAME') }}"
store_rds_apply_immediately:               "{{ lookup('env', 'STORE_RDS_APPLY_IMMEDIATELY') }}"
store_rds_instance_type:                   "{{ lookup('env', 'STORE_RDS_INSTANCE_TYPE') }}"
store_rds_multi_az:                        "{{ lookup('env', 'STORE_RDS_MULTI_AZ') }}"
store_rds_name:                            "{{ lookup('env', 'STORE_RDS_NAME') }}"
store_rds_postgres_version:                "{{ lookup('env', 'STORE_RDS_POSTGRES_VERSION') }}"
store_rds_storage_size:                    "{{ lookup('env', 'STORE_RDS_STORAGE_SIZE') }}"
store_rds_storage_type:                    "{{ lookup('env', 'STORE_RDS_STORAGE_TYPE') }}"
terraform_version:                         "{{ lookup('env', 'TERRAFORM_VERSION') }}"
tf_manager_baseimage_version:              "{{ lookup('env', 'TF_MANAGER_PHUSION_BASEIMAGE_VERSION') }}"
tf_manager_pg_version:                     "{{ lookup('env', 'TF_MANAGER_PG_VERSION') }}"
version:                                   "{{ lookup('env', 'VERSION') }}"
yq_version:                                "{{ lookup('env', 'YQ_VERSION') }}"
