---
ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

issue_template:
  - changed-files:
      - any-glob-to-any-file: ".github/ISSUE_TEMPLATE/*"

roles:
  - changed-files:
      - any-glob-to-any-file: "roles/**/*"

makefile:
  - changed-files:
      - any-glob-to-any-file: "Makefile"

inventory:
  - changed-files:
      - any-glob-to-any-file: "inventory/**/*"

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
  - changed-files:
    - any-glob-to-any-file: assets/*

feature:
  - head-branch: ['^feature', 'feature']

release:
  - base-branch: 'main'
