---
# Area
- name: ci
  color: "9ac2f2"
  description: >-
    Changes made in the github directory

- name: roles
  color: "2ec27e"
  description: >-
    Changes made in the roles directory

- name: issue_template
  color: "72ccf3"
  description: >-
    Changes made in the issue_template directory

- name: makefile
  color: "009900"
  description: >-
    Changes made in Makefile

- name: inventory
  color: "009900"
  description: >-
    Changes made in inventory directory

- name: documentation
  color: "009900"
  description: >-
    Changes made in documentation

- name: feature
  color: "009900"
  description: >-
    Feature

# Renovate
- name: renovate/container
  color: "e5a50a"

- name: renovate/github-action
  color: "f5c211"

- name: renovate/github-release
  color: "f6d32d"

- name: renovate
  color: "e5a50a"
  description: >-
    Updates from Renovate Bot

# Semantic Type
- name: dep/patch
  color: "FFEC19"

- name: dep/minor
  color: "FF9800"

- name: dep/major
  color: "F6412D"

# Size
- name: size/S
  color: "dd8bde"
  description: >-
    Denotes a PR that changes 10-29 lines, ignoring generated files

- name: size/M
  color: "c161cc"
  description: >-
    Denotes a PR that changes 30-99 lines, ignoring generated files

- name: size/L
  color: "9241ad"
  description: >-
    Denotes a PR that changes 100-499 lines, ignoring generated files

- name: size/XL
  color: "823d9d"
  description: >-
    Denotes a PR that changes 500-999 lines, ignoring generated files

- name: size/XXL
  color: "613584"
  description: >-
    Denotes a PR that changes 1000+ lines, ignoring generated files

# Uncategorized
- name: do-not-merge
  color: "ee0701"

- name: docs
  color: "F4D1B7"

- name: enhancement
  color: "84b6eb"

- name: link-checker
  color: "7B55D7"

- name: question
  color: "cc317c"

# Issue categories
- name: documentation
  color: "009900"
  description: >-
    Changes made in documentation

- name: bug
  color: "B60205"

- name: enhancement
  color: "a2eeef"

- name: "help wanted"
  color: "008672"

- name: wontfix
  color: "ffffff"

- name: "support"
  color: "ffffff"

- name: "incomplete-template"
  color: "ffffff"

# CI Status
- name: "precommit:ok"
  color: "0E8A16"
  description: >-
    CI status: pre-commit validation successful

- name: "precommit:failed"
  color: "D93F0B"
  description: >-
    CI status: pre-commit validation failed

- name: "changelog:ok"
  color: "0E8A16"
  description: >-
    CI status: changelog validation successful

- name: "changelog:failed"
  color: "D93F0B"
  description: >-
    CI status: changelog validation failed

- name: "lint:ok"
  color: "0E8A16"
  description: >-
    CI status: linting successful

- name: "lint:failed"
  color: "D93F0B"
  description: >-
    CI status: linting failed

- name: "install:ok"
  color: "0E8A16"
  description: >-
    CI status: install successful

- name: "install:failed"
  color: "D93F0B"
  description: >-
    CI status: install failed

- name: feature
  color: "009900"
  description: >-
    Feature

- name: issue_template
  color: "72ccf3"
  description: >-
    Changes made in the issue_template directory

- name: makefile
  color: "613583"
  description: >-
    Changes made in Makefile
