---
- name: Update and upgrade Debian packages, Install non-free firmware, Intel GPU tools and other tools.
  block:
  # - name: Ensure multipath.conf exists with correct content
  #   template:
  #     src: multipath.conf.j2
  #     dest: /etc/multipath.conf
  #     mode: '0644'

  # - name: Ensure hostspath.conf exists with correct content
  #   template:
  #     src: hostspath.conf.j2
  #     dest: /etc/hosts
  #     mode: '0644'

  - name: Ensure /etc/apt/apt.conf.d/00aptproxy exists with correct content
    template:
      src: apt-cacher.conf.j2
      dest: /etc/apt/apt.conf.d/00aptproxy
      mode: '0644'

  - name: Ensure non-free repository is enabled
    lineinfile:
      path: /etc/apt/sources.list
      line: "deb http://deb.debian.org/debian/ bookworm main contrib non-free
        non-free-firmware"
      state: present

  - name: Update apt repository cache
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      pkg:
      - cryptsetup
      - dnsutils
      - firmware-misc-nonfree
      # - intel-gpu-tools
      # - intel-media-va-driver-non-free
      - iotop
      - iperf
      - iptables
      - jq
      - mc
      - neofetch
      - nfs-common
      - nmap
      - open-iscsi
      - parted
      - qemu-guest-agent
      - util-linux
      - vim
      state: present

  - name: Ensure neofetch exists with correct content
    lineinfile:
      path: /home/ansible/.bashrc
      line: "neofetch"
      state: present

  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes

  - name: Start the systemd service for qemu-guest-agent if it is not started
    systemd:
      name: qemu-guest-agent
      enabled: yes
      state: started

  # - name: Install specific kernel image
  #   apt:
  #     name: linux-image-6.10.6+bpo-cloud-amd64
  #     state: present

  - name: Ensure iscsi_tcp is present in /etc/modules
    lineinfile:
      path: /etc/modules
      line: 'iscsi_tcp'
      state: present

  - name: Remove nfs-common service file
    file:
      path: /lib/systemd/system/nfs-common.service
      state: absent

  - name: Reload systemd daemon
    command: systemctl daemon-reload

  - name: Start the systemd service for nfs-common if it is not started
    systemd:
      name: nfs-common
      enabled: yes
      state: started

  - name: Load the kernel module
    modprobe:
      name: iscsi_tcp
      state: present

  - name: Start the systemd service for iscsid if it is not started
    systemd:
      name: iscsid
      enabled: yes
      state: started

  - name: Check if a reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot the server if required
    reboot:
      msg: "Reboot initiated by Ansible for package updates"
    when: reboot_required_file.stat.exists

  - name: Autoremove unnecessary packages
    apt:
      autoremove: yes
