---
- name: "Update and upgrade Debian packages"
  block:
    # - name: Ensure multipath.conf exists with correct content
    #   ansible.builtin.template:
    #     src: multipath.conf.j2
    #     dest: /etc/multipath.conf
    #     mode: '0644'

    # - name: Ensure hostspath.conf exists with correct content
    #   ansible.builtin.template:
    #     src: hostspath.conf.j2
    #     dest: /etc/hosts
    #     mode: '0644'

    - name: "Ensure /etc/apt/apt.conf.d/00aptproxy exists with correct content"
      ansible.builtin.template:
        src: apt-cacher.conf.j2
        dest: /etc/apt/apt.conf.d/00aptproxy
        mode: '0644'

    - name: "Ensure non-free repository is enabled"
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://deb.debian.org/debian/ bookworm main contrib non-free
          non-free-firmware"
        state: present

    - name: "Update apt repository cache"
      ansible.builtin.apt:
        update_cache: true

    - name: "Install required packages"
      ansible.builtin.apt:
        pkg:
          - cryptsetup
          - dnsutils
          - firmware-misc-nonfree
          # - intel-gpu-tools
          # - intel-media-va-driver-non-free
          - iotop
          - iperf
          - iptables
          - jq
          - mc
          - neofetch
          - nfs-common
          - nmap
          - open-iscsi
          - parted
          - qemu-guest-agent
          - util-linux
          - vim
        state: present

    - name: "Ensure neofetch exists with correct content"
      ansible.builtin.lineinfile:
        path: /home/ansible/.bashrc
        line: "neofetch"
        state: present

    - name: "Upgrade all packages to the latest version"
      ansible.builtin.apt:
        upgrade: true

    - name: "Start the systemd service for qemu-guest-agent if it is not started"
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started

    # - name: Install specific kernel image
    #   ansible.builtin.apt:
    #     name: linux-image-6.10.6+bpo-cloud-amd64
    #     state: present

    - name: "Ensure iscsi_tcp is present in /etc/modules"
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: 'iscsi_tcp'
        state: present

    - name: "Remove nfs-common service file"
      ansible.builtin.file:
        path: /lib/systemd/system/nfs-common.service
        state: absent

    - name: "Reload systemd daemon"
      ansible.builtin.command: systemctl daemon-reload

    - name: "Start the systemd service for nfs-common if it is not started"
      ansible.builtin.systemd:
        name: nfs-common
        enabled: true
        state: started

    - name: "Load the kernel module"
      community.general.modprobe:
        name: iscsi_tcp
        state: present

    - name: "Start the systemd service for iscsid if it is not started"
      ansible.builtin.systemd:
        name: iscsid
        enabled: true
        state: started

    - name: "Check if a reboot is required"
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: "Reboot the server if required"
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for package updates"
      when: reboot_required_file.stat.exists

    - name: "Autoremove unnecessary packages"
      ansible.builtin.apt:
        autoremove: true
