; [k3s_cluster:vars]
; ansible_user=ansible
; k3s_version=v1.33.0+k3s1

[master]
dev-master-0.lab.e-liberty.org node_name=dev-master-0
; dev-master-1.lab.e-liberty.org node_name=dev-master-1
; dev-master-2.lab.e-liberty.org node_name=dev-master-2

[node]
dev-node-0.lab.e-liberty.org node_name=dev-node-0
dev-node-1.lab.e-liberty.org node_name=dev-node-1
; dev-node-2.lab.e-liberty.org node_name=dev-node-2

[k3s_cluster:children]
master
node

[storage_servers]
dev-node-0.lab.e-liberty.org
dev-node-1.lab.e-liberty.org
; dev-node-2.lab.e-liberty.org
