[master]
prod-master-0.lab.e-liberty.org node_name=prod-master-0
; prod-master-1.lab.e-liberty.org node_name=prod-master-1
; prod-master-2.lab.e-liberty.org node_name=prod-master-2

[node]
prod-node-0.lab.e-liberty.org node_name=prod-node-0
prod-node-1.lab.e-liberty.org node_name=prod-node-1
; prod-node-2.lab.e-liberty.org node_name=prod-node-2

[k3s_cluster:children]
master
node

[storage_servers]
prod-node-0.lab.e-liberty.org
prod-node-1.lab.e-liberty.org
; prod-node-2.lab.e-liberty.org
