---
- name: Patch kubeconfig with env_name template
  block:
  - name: Read raw kubeconfig
    ansible.builtin.slurp:
      src: "{{ ansible_user_dir }}/.kube/config"
    register: raw_kubeconfig

  - name: Parse kubeconfig YAML
    set_fact:
      kubeconfig_content: "{{ raw_kubeconfig['content'] | b64decode | from_yaml }}"

  - name: Set template variables
    set_fact:
      ca_data: "{{ kubeconfig_content.clusters[0].cluster['certificate-authority-data'] }}"
      server: "{{ kubeconfig_content.clusters[0].cluster.server }}"
      client_cert: "{{ kubeconfig_content.users[0].user['client-certificate-data'] }}"
      client_key: "{{ kubeconfig_content.users[0].user['client-key-data'] }}"

  - name: Ensure kubeconfig target directory exists
    ansible.builtin.file:
      path: "./target/{{ env_name }}/.kube"
      state: directory
      mode: '0700'
    delegate_to: localhost
    run_once: true
    become: false

  - name: Render kubeconfig template with custom env_name
    ansible.builtin.template:
      src: "templates/kubeconfig.yml.j2"
      dest: "./target/{{ env_name }}/.kube/config"
      mode: '0600'
    delegate_to: localhost
    run_once: true
    become: false
