---
- name: "Check if swap is active"
  ansible.builtin.command: >
    swapon --show
  register: swap_active
  failed_when: false
  changed_when: false

- name: "Disable swap at runtime"
  ansible.builtin.command: swapoff -a
  when: swap_active.rc == 0  # Only if swap is active

- name: "Disable swap at boot"
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  # loop: ["none", "swap"]
  loop: "{{ lookup('file', '/etc/fstab').split('\n') | map('regex_search',
        '^([^\\s]+)\\s+swap\\s+') | map('regex_replace', '^([^\\s]+)\\s+swap\\s+.*', '\\1') | list }}"
