---
- name: Disable swap memory
  ansible.builtin.include_tasks: disable_swap.yml
  tags: longhorn

- name: Prepare data disks for storage before installing Longhorn
  ansible.builtin.include_tasks: format-disks.yaml
  tags: longhorn
