---
- name: Update and upgrade Debian packages
  ansible.builtin.include_tasks: packages.yml
  tags: packages

- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items: "{{ packages }}"
  tags: packages

- name: Check system
  ansible.builtin.include_tasks: checksystem.yml
  tags: packages
