---
name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**/.gitignore'
      - '**/FUNDING.yml'
      - '**/host.ini'
      - '**/*.md'
      - '**/.editorconfig'
      - '**/ansible.cfg'
      - '**/deploy.sh'
      - '**/LICENSE'
      - '**/reboot.sh'
      - '**/reset.sh'

jobs:
  size:
    uses: ./.github/workflows/label-size.yml

  labeler:
    uses: ./.github/workflows/labeler.yml
    needs: [size]

  sync:
    uses: ./.github/workflows/sync-labels.yml
    needs: [labeler]

  lint:
    uses: ./.github/workflows/linter.yml
    needs: [sync]

  test:
    uses: ./.github/workflows/test.yml
    needs: [lint]
