---
name: Labels sync
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  label-sync:
    name: Labels sync
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Labels sync
      uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
      with:
        config-file: .github/labels.yaml
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-other-labels: true
