---
name: Labeler
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

jobs:
  labeler:
    name: Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          repository: ''

      - name: Labeler
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yaml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: false
