---
name: SuperLint Code Base
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint_code_base-ci:
    name: Lint Code Base
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: super-linter
        uses: docker://github/super-linter:slim-latest
        env:
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          FIX_ANSIBLE: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
